apiVersion: v1
kind: Service
metadata:
  name: trillo-rt
  namespace: trillo
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <PASTE CERTIFICATE ARN HERE>
spec:
  selector:
    app: trillo-rt
  ports:
    - name: https
      port: 443
      targetPort: 8020
      protocol: TCP
  type: LoadBalancer # Internet facing ELB
