AWSTemplateFormatVersion: "2010-09-09"

Description: >
    This template creates a bastion host which is needed for debugging and administrative purposes only.

    Reference: https://github.com/awslabs/startup-kit-templates/blob/master/bastion.cfn.yml

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  PublicSubnet:
    Description: Choose the internet-facing PublicSubnet
    Type: AWS::EC2::Subnet::Id

  SecurityGroup:
    Description: Select the Security Group to apply to the BastionHost
    Type: AWS::EC2::SecurityGroup::Id

  KeyName:
    Description: EC2 key pair name for bastion host SSH access
    Type: AWS::EC2::KeyPair::KeyName
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Key pair name can contain only ASCII characters.

Mappings:

  AMIMap:  # Amazon Linux AMI
    ap-northeast-1:
      AMI: ami-4af5022c
    ap-northeast-2:
      AMI: ami-8663bae8
    ap-south-1:
      AMI: ami-d7abd1b8
    ap-southeast-1:
      AMI: ami-fdb8229e
    ap-southeast-2:
      AMI: ami-30041c53
    eu-west-1:
      AMI: ami-ebd02392
    eu-west-2:
      AMI: ami-489f8e2c
    eu-central-1:
      AMI: ami-657bd20a
    sa-east-1:
      AMI: ami-d27203be
    us-east-1:
      AMI: ami-4fffc834
    us-east-2:
      AMI:  ami-ea87a78f
    us-west-1:
      AMI: ami-3a674d5a
    us-west-2:
      AMI: ami-aa5ebdd2
    ca-central-1:
      AMI: ami-5ac17f3e

Resources:

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !FindInMap [AMIMap, !Ref "AWS::Region", AMI]
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Bastion Host

  BastionEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref BastionHost
      Domain: vpc

Outputs:

  BastionIP:
    Description: EIP for bastion host
    Value: !Ref BastionEIP
